TerminZaVozacka/Models/Prijava.cs
using Org.BouncyCastle.Asn1.Cms;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TerminZaVozacka.Models
{
    public class Prijava
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public String UserName { get; set; }
        [Key]
        public int Id{ get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public string Category { get; set; }
        [Required]
        public string IdentificationNumber { get; set; }
        [Required]
        public Boolean IsAccepted { get; set; }
        [Required]

        public DateTime CreationTime { get; set; }
        [Required]
        public DateTime DateTime { get; set; }
        [Required]
        public TimeSpan Time { get; set; }
        [Required]
        public int LicnaKartaId { get; set; }
        [Required]
        public int Zdravstveno { get; set; }
        [Required]
        public int Obrazovanie { get; set; }
        [Required]
        public int PotvrdaZaCasovi { get; set; }
        [Required]
        public int Uplatnica { get; set; }

    }
}

TerminZaVozacka/Controllers/PrijavasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using TerminZaVozacka.Models;
using EntityState = System.Data.Entity.EntityState;
using Microsoft.VisualBasic;
using System.IO;
using TerminZaVozacka.Migrations;
using TeorijaPrijava = TerminZaVozacka.Models.TeorijaPrijava;
using DateTime = System.DateTime;

namespace TerminZaVozacka.Controllers
{
    [Authorize(Roles = "User")]
    public class PrijavasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        

        // GET: Prijavas
        public ActionResult Index()
        {
            var data = from prijava in db.Prijavas
                       where prijava.UserName == User.Identity.Name
                       where prijava.IsAccepted == false
                       select prijava;
            return View("Index",data.ToList());
        }

        public ActionResult Accepted()
        {
            var data = from prijava in db.Prijavas
                       where prijava.UserName == User.Identity.Name
                       where prijava.IsAccepted == true
                       select prijava;
            return View(db.Prijavas.ToList());
        }

        // GET: Prijavas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prijava prijava = db.Prijavas.Find(id);
            if (prijava == null)
            {
                return HttpNotFound();
            }
            return View(prijava);
        }

    
        

        public ActionResult CreateExam()
        {
            PrijavaTypeModel model = new PrijavaTypeModel();
           
            return View(model);
        }


        // POST: Prijavas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateExam(PrijavaTypeModel model)
        {
       
            FileModel f = SaveImage(model.LicnaKarta);
            FileModel f1 = SaveImage(model.Uplatnica);
            teorijaPrijava.LicnaKartaId = model.Prijava.LicnaKartaId;
            teorijaPrijava.Uplatnica = model.Prijava.Uplatnica;
         

            return this.CheckExam(teorijaPrijava);
        }

        public ActionResult CheckExam(TeorijaPrijava model)
        {
            if (ModelState.IsValid)
            {
                db.Prijavas.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return null ;
        }

        // GET: Prijavas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prijava prijava = db.Prijavas.Find(id);
            if (prijava == null)
            {
                return HttpNotFound();
            }
            return View(prijava);
        }

        // POST: Prijavas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Prijava prijava)
        {
            Prijava find = db.Prijavas.Find(prijava.Id);
            if (find != null)
            {
                find.Name = prijava.Name;
                find.Surname = prijava.Surname;
                find.IdentificationNumber = prijava.IdentificationNumber;
                db.Entry(find).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(prijava);
        }

        // GET: Prijavas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prijava prijava = db.Prijavas.Find(id);
            if (prijava == null)
            {
                return HttpNotFound();
            }
            return View(prijava);
        }

        // POST: Prijavas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prijava prijava = db.Prijavas.Find(id);
            db.Prijavas.Remove(prijava);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public FileModel SaveImage(HttpPostedFileBase httpPosted)
        {
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(httpPosted.InputStream))
            {
                bytes = br.ReadBytes(httpPosted.ContentLength);
            }
            ApplicationDbContext entities = new ApplicationDbContext();
            FileModel fileModel = entities.FileModels.Add(new FileModel
            {
                Name = Path.GetFileName(httpPosted.FileName),
                ContentType = httpPosted.ContentType,
                Data = bytes
            });
            entities.SaveChanges();

            return fileModel;
        }
// GET: Prijavas/Create
        public ActionResult Create()
        {
            PrijavaTypeModel model = new PrijavaTypeModel();
            model.Types = new List<string>() {
                "A1", "A2", "AM", "B","B17","F","G"
                ,"A", "A1", "BE", "C","CE", "C1", "C1E", "D", "DE","D1","D1E"
            };
            return View(model);
        }
        
        public ActionResult Valid(PrijavaTypeModel model)
        {
            if (ModelState.IsValid)
            {
                return this.SelectType(model);
            }
            
            return View("Create", model);
        }

        public ActionResult SelectType(PrijavaTypeModel model)
        {

            FileModel Licna = SaveImage(model.LicnaKarta);
            FileModel Uplatnica = SaveImage(model.Uplatnica);
            FileModel Obrazovanie = SaveImage(model.Obrazovanie);
            FileModel Zdravstveno = SaveImage(model.Zdravstveno);
            FileModel Potvrda = SaveImage(model.PotvrdaZaCasovi);

            string[] bezPrethodna = new string[]
            {
                "A1", "A2", "AM", "B","B17","F","G"
            };

            string[] soPrethodna = new string[]
            {
                "A", "A1", "BE", "C","CE", "C1", "C1E", "D", "DE","D1","D1E"
            };

            var type = model.SelectedItem;
            if (bezPrethodna.Contains(type) ) {
                BTypePrijava d = new BTypePrijava();
                d.Id = model.Prijava.Id;
                d.UserName = model.Prijava.UserName;
                d.IdentificationNumber = model.Prijava.IdentificationNumber;
                d.IsAccepted = model.Prijava.IsAccepted;
                d.Name = model.Prijava.Name;
                d.Surname = model.Prijava.Surname;
                d.Category = model.Prijava.Category ;
                d.Type = type;
                d.LicnaKartaId = Licna.Id;
                d.Uplatnica = Uplatnica.Id;
                d.Obrazovanie = Obrazovanie.Id;
                d.Zdravstveno = Zdravstveno.Id;
                d.PotvrdaZaCasovi = Potvrda.Id;            
                d.DateTime = DateTime.Now;
                d.Time = new TimeSpan();
                d.CreationTime = DateTime.Now;
                return RedirectToAction("CheckSelectTypeB", d);
            }
            if (soPrethodna.Contains(type))
            {
                ATypePrijava d = new ATypePrijava();
                d.Id = model.Prijava.Id;
                d.UserName = model.Prijava.UserName;
                d.IdentificationNumber = model.Prijava.IdentificationNumber;
                d.IsAccepted = model.Prijava.IsAccepted;
                d.Name = model.Prijava.Name;
                d.Surname = model.Prijava.Surname;
                d.Category = model.Prijava.Category;
                d.Type = type;
                d.LicnaKartaId = Licna.Id;
                d.Uplatnica = Uplatnica.Id;
                d.Obrazovanie = Obrazovanie.Id;
                d.Zdravstveno = Zdravstveno.Id;
                d.PotvrdaZaCasovi = Potvrda.Id;
                d.DateTime = DateTime.Now;
                d.Time = new TimeSpan();
                d.CreationTime = DateTime.Now;
                return PartialView("ATypeSelect", d);
            }

            return null;
        }

        

        
        public ActionResult CheckSelectTypeB(BTypePrijava model)

        {
            if (ModelState.IsValid)
            {
                db.Prijavas.Add(model);
                db.SaveChanges();
                return PartialView("Success");
            }
            PrijavaTypeModel d = new PrijavaTypeModel() 
            {
                Prijava = new Prijava(),
                Types = new List<string>() { "B", "A", "Employee" }
            };
            d.Prijava.Id = model.Id;
            d.Prijava.UserName = model.UserName;
            d.Prijava.IdentificationNumber = model.IdentificationNumber;
            d.Prijava.IsAccepted = model.IsAccepted;
            d.Prijava.Category = "B";
            d.Prijava.Name = model.Name;
            d.Prijava.Surname = model.Surname;
            return View("Create", d);
        }

TerminZaVozacka/Views/Prijavas/ATypeSelect.cshtml
@model TerminZaVozacka.Models.ATypePrijava

@using (Html.BeginForm("CheckSelectTypeA", "Prijavas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ATypeDecorator</h4>
    <hr />
    @Html.HiddenFor(m => m.Id);
    @Html.HiddenFor(m => m.IdentificationNumber);
    @Html.HiddenFor(m => m.IsAccepted);
    @Html.HiddenFor(m => m.Type);
    @Html.HiddenFor(m => m.UserName);
    @Html.HiddenFor(m => m.Name);
    @Html.HiddenFor(m => m.Surname);
    @Html.HiddenFor(m => m.LicnaKartaId)
    @Html.HiddenFor(m => m.DateTime)
    @Html.HiddenFor(m => m.Time)
    @Html.HiddenFor(m => m.Obrazovanie)
    @Html.HiddenFor(m => m.Zdravstveno)
    @Html.HiddenFor(m => m.PotvrdaZaCasovi)
    @Html.HiddenFor(m => m.Uplatnica)
    @Html.HiddenFor(m => m.Category)
    @Html.HiddenFor(m => m.CreationTime)
    <div class="form-group">
        @Html.LabelFor(model => model.PrethodnaVozackaId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="PrethodnaVozacka" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TerminZaVozacka/Views/Prijavas/Accepted.cshtml
@model IEnumerable<TerminZaVozacka.Models.Prijava>

@{
    ViewBag.Title = "Accepted";
}

<h2>Accepted</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAccepted)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdentificationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAccepted)
        </td>
   
    </tr>
}

</table>

TerminZaVozacka/Views/Prijavas/Create.cshtml
@model TerminZaVozacka.Models.PrijavaTypeModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



@Html.AntiForgeryToken()

<div>
    @using (Ajax.BeginForm("Valid", "Prijavas", new AjaxOptions
    { HttpMethod = "POST", UpdateTargetId = "dd" }, new { id = "form", enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            <h4>Prijava</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.Prijava.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prijava.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prijava.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prijava.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prijava.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prijava.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prijava.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prijava.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prijava.Type, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Prijava.IdentificationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prijava.IdentificationNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prijava.IdentificationNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LicnaKarta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="LicnaKarta" />
                    @Html.ValidationMessageFor(model => model.LicnaKarta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Zdravstveno, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Zdravstveno" />
                    @Html.ValidationMessageFor(model => model.LicnaKarta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Obrazovanie, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Obrazovanie" />
                    @Html.ValidationMessageFor(model => model.LicnaKarta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PotvrdaZaCasovi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="PotvrdaZaCasovi" />
                    @Html.ValidationMessageFor(model => model.LicnaKarta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Uplatnica, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Uplatnica" />
                    @Html.ValidationMessageFor(model => model.LicnaKarta, "", new { @class = "text-danger" })
                </div>
            </div>


            @Html.HiddenFor(model => model.Prijava.UserName, new { @Value = User.Identity.Name })
            @Html.HiddenFor(model => model.Prijava.IsAccepted, new { @Value = false });
            @Html.HiddenFor(model => model.Prijava.DateTime, new { @Value = DateTime.Now })
            @Html.HiddenFor(model => model.Prijava.CreationTime, new { @Value = DateTime.Now })
            @Html.HiddenFor(model => model.Prijava.Time, new { @Value = new TimeSpan() });
            @Html.HiddenFor(model => model.Prijava.Category, new { @Value = "Praksa" })
            @Html.HiddenFor(model => model.Types, new { @Value = Model.Types })
            @Html.HiddenFor(model => model.Prijava.Id, new { @Value = 0 })
            @Html.DropDownListFor(m => m.SelectedItem, new SelectList(Model.Types))

            <input type="submit" />



        </div>

            }
        
<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<div id="dd">

</div>

TerminZaVozacka/Views/Prijavas/CreateExam.cshtml
@model TerminZaVozacka.Models.PrijavaTypeModel

@{
    ViewBag.Title = "CreateExam";
}

<h2>CreateExam</h2>

@using (Html.BeginForm("CreateExam", "Prijavas", FormMethod.Post, new { id = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Prijava</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Prijava.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prijava.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prijava.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prijava.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prijava.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prijava.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prijava.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prijava.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prijava.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prijava.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prijava.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prijava.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prijava.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prijava.Category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prijava.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prijava.IdentificationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prijava.IdentificationNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prijava.IdentificationNumber, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.LicnaKarta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input name="LicnaKarta" type="file"></input>
            @Html.ValidationMessageFor(model => model.LicnaKarta, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Uplatnica, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input name="Uplatnica" type="file"></input>
            @Html.ValidationMessageFor(model => model.Uplatnica, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Prijava.UserName, new { @Value = User.Identity.Name })
    @Html.HiddenFor(model => model.Prijava.IsAccepted, new { @Value = false });
    @Html.HiddenFor(model => model.Prijava.DateTime, new { @Value = DateTime.Now })
    @Html.HiddenFor(model => model.Prijava.Time, new { @Value = false });
    @Html.HiddenFor(model => model.Prijava.Category)
    @Html.HiddenFor(model => model.Prijava.CreationTime, new { @Value = DateTime.Now })


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TerminZaVozacka/Views/Prijavas/Delete.cshtml
@model TerminZaVozacka.Models.Prijava

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Prijava</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentificationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAccepted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAccepted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TerminZaVozacka/Views/Prijavas/Details.cshtml
@model TerminZaVozacka.Models.Prijava

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Prijava</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentificationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentificationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAccepted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAccepted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TerminZaVozacka/Views/Prijavas/SelectType.cshtml
@model TerminZaVozacka.Models.BTypePrijava

@using (Html.BeginForm("CheckSelectTypeB", "Prijavas")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>BTypeDecorator</h4>

  

    @Html.HiddenFor(m => m.Id);
    @Html.HiddenFor(m => m.IdentificationNumber);
    @Html.HiddenFor(m => m.IsAccepted);
    @Html.HiddenFor(m => m.Type);
    @Html.HiddenFor(m => m.UserName);
    @Html.HiddenFor(m => m.Name);
    @Html.HiddenFor(m => m.Surname);
    @Html.HiddenFor(m => m.LicnaKartaId)
    @Html.HiddenFor(m => m.DateTime)
    @Html.HiddenFor(m => m.Time)
    @Html.HiddenFor(m => m.Obrazovanie)
    @Html.HiddenFor(m => m.Zdravstveno)
    @Html.HiddenFor(m => m.PotvrdaZaCasovi)
    @Html.HiddenFor(m => m.Uplatnica)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TerminZaVozacka/Views/Prijavas/Success.cshtml
<div>Successful!</div>